package md.factorydream.entites;
// Generated Apr 13, 2016 10:19:57 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Access generated by hbm2java
 */
@Entity
@Table(name = "access", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "access_name")
)

public class Access implements java.io.Serializable {

    private int id;
    private StatusCod statusCod;
    private String accessName;
    private String accessDescription;
    private Set<RoleAccess> roleAccesses = new HashSet<RoleAccess>(0);

    public Access() {
    }

    public Access(int id, String accessName) {
        this.id = id;
        this.accessName = accessName;
    }

    public Access(int id, StatusCod statusCod, String accessName, String accessDescription, Set<RoleAccess> roleAccesses) {
        this.id = id;
        this.statusCod = statusCod;
        this.accessName = accessName;
        this.accessDescription = accessDescription;
        this.roleAccesses = roleAccesses;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_status_code")
    public StatusCod getStatusCod() {
        return this.statusCod;
    }

    public void setStatusCod(StatusCod statusCod) {
        this.statusCod = statusCod;
    }

    @Column(name = "access_name", unique = true, nullable = false, length = 10)
    public String getAccessName() {
        return this.accessName;
    }

    public void setAccessName(String accessName) {
        this.accessName = accessName;
    }

    @Column(name = "access_description")
    public String getAccessDescription() {
        return this.accessDescription;
    }

    public void setAccessDescription(String accessDescription) {
        this.accessDescription = accessDescription;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "access")
    public Set<RoleAccess> getRoleAccesses() {
        return this.roleAccesses;
    }

    public void setRoleAccesses(Set<RoleAccess> roleAccesses) {
        this.roleAccesses = roleAccesses;
    }

}
