package md.factorydream.entites;
// Generated Apr 13, 2016 10:19:57 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EmployeesJobs generated by hbm2java
 */
@Entity
@Table(name = "employees_jobs", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {"id_employee", "id_job"})
)

public class EmployeesJobs implements java.io.Serializable {

    private int id;
    private Employees employees;
    private Jobs jobs;

    public EmployeesJobs() {
    }

    public EmployeesJobs(int id, Employees employees, Jobs jobs) {
        this.id = id;
        this.employees = employees;
        this.jobs = jobs;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_employee", nullable = false)
    public Employees getEmployees() {
        return this.employees;
    }

    public void setEmployees(Employees employees) {
        this.employees = employees;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_job", nullable = false)
    public Jobs getJobs() {
        return this.jobs;
    }

    public void setJobs(Jobs jobs) {
        this.jobs = jobs;
    }

}
