package md.factorydream.entites;
// Generated Apr 13, 2016 10:19:57 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Equipment generated by hbm2java
 */
@Entity
@Table(name = "equipment", schema = "public"
)

public class Equipment implements java.io.Serializable {

    private int id;
    private Departments departments;
    private StatusCod statusCod;
    private Users users;
    private String name;
    private String equipmentDescription;
    private Date lastUpdateDate;
    private Set<Appointment> appointments = new HashSet<Appointment>(0);

    public Equipment() {
    }

    public Equipment(int id, Departments departments, Users users, String name, String equipmentDescription) {
        this.id = id;
        this.departments = departments;
        this.users = users;
        this.name = name;
        this.equipmentDescription = equipmentDescription;
    }

    public Equipment(int id, Departments departments, StatusCod statusCod, Users users, String name, String equipmentDescription, Date lastUpdateDate, Set<Appointment> appointments) {
        this.id = id;
        this.departments = departments;
        this.statusCod = statusCod;
        this.users = users;
        this.name = name;
        this.equipmentDescription = equipmentDescription;
        this.lastUpdateDate = lastUpdateDate;
        this.appointments = appointments;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_department", nullable = false)
    public Departments getDepartments() {
        return this.departments;
    }

    public void setDepartments(Departments departments) {
        this.departments = departments;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_status_code")
    public StatusCod getStatusCod() {
        return this.statusCod;
    }

    public void setStatusCod(StatusCod statusCod) {
        this.statusCod = statusCod;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user_last_update", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "equipment_description", nullable = false)
    public String getEquipmentDescription() {
        return this.equipmentDescription;
    }

    public void setEquipmentDescription(String equipmentDescription) {
        this.equipmentDescription = equipmentDescription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update_date", length = 29)
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "equipment")
    public Set<Appointment> getAppointments() {
        return this.appointments;
    }

    public void setAppointments(Set<Appointment> appointments) {
        this.appointments = appointments;
    }

}
