package md.factorydream.entites;
// Generated Apr 13, 2016 10:19:57 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * EventParameters generated by hbm2java
 */
@Entity
@Table(name = "event_parameters", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {"id_param_name", "id_event"})
)

public class EventParameters implements java.io.Serializable {

    private long id;
    private Events events;
    private ParamNames paramNames;
    private Users users;
    private String value;
    private String note;
    private Date lastUpdateDate;
    private Short idStatusCode;

    public EventParameters() {
    }

    public EventParameters(long id, Events events, ParamNames paramNames, Users users, String value) {
        this.id = id;
        this.events = events;
        this.paramNames = paramNames;
        this.users = users;
        this.value = value;
    }

    public EventParameters(long id, Events events, ParamNames paramNames, Users users, String value, String note, Date lastUpdateDate, Short idStatusCode) {
        this.id = id;
        this.events = events;
        this.paramNames = paramNames;
        this.users = users;
        this.value = value;
        this.note = note;
        this.lastUpdateDate = lastUpdateDate;
        this.idStatusCode = idStatusCode;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_event", nullable = false)
    public Events getEvents() {
        return this.events;
    }

    public void setEvents(Events events) {
        this.events = events;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_param_name", nullable = false)
    public ParamNames getParamNames() {
        return this.paramNames;
    }

    public void setParamNames(ParamNames paramNames) {
        this.paramNames = paramNames;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user_last_update", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "value", nullable = false, length = 250)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Column(name = "note", length = 250)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update_date", length = 29)
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @Column(name = "id_status_code")
    public Short getIdStatusCode() {
        return this.idStatusCode;
    }

    public void setIdStatusCode(Short idStatusCode) {
        this.idStatusCode = idStatusCode;
    }

}
