package md.factorydream.entites;
// Generated Apr 27, 2016 2:37:35 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Languages generated by hbm2java
 */
@Entity
@Table(name = "languages", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "language_cod")
)
public class Languages implements java.io.Serializable {

    private short id;
    private StatusCod statusCod;
    private String languageCod;
    private String languageDescription;
    private Set<TranslateDictionary> translateDictionaries = new HashSet<TranslateDictionary>(0);
    private Set<Users> userses = new HashSet<Users>(0);

    public Languages() {
    }

    public Languages(short id, String languageCod, String languageDescription) {
        this.id = id;
        this.languageCod = languageCod;
        this.languageDescription = languageDescription;
    }

    public Languages(short id, StatusCod statusCod, String languageCod, String languageDescription, Set<TranslateDictionary> translateDictionaries, Set<Users> userses) {
        this.id = id;
        this.statusCod = statusCod;
        this.languageCod = languageCod;
        this.languageDescription = languageDescription;
        this.translateDictionaries = translateDictionaries;
        this.userses = userses;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public short getId() {
        return this.id;
    }

    public void setId(short id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_status_code")
    public StatusCod getStatusCod() {
        return this.statusCod;
    }

    public void setStatusCod(StatusCod statusCod) {
        this.statusCod = statusCod;
    }

    @Column(name = "language_cod", unique = true, nullable = false, length = 2)
    public String getLanguageCod() {
        return this.languageCod;
    }

    public void setLanguageCod(String languageCod) {
        this.languageCod = languageCod;
    }

    @Column(name = "language_description", nullable = false, length = 200)
    public String getLanguageDescription() {
        return this.languageDescription;
    }

    public void setLanguageDescription(String languageDescription) {
        this.languageDescription = languageDescription;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "languages")
    public Set<TranslateDictionary> getTranslateDictionaries() {
        return this.translateDictionaries;
    }

    public void setTranslateDictionaries(Set<TranslateDictionary> translateDictionaries) {
        this.translateDictionaries = translateDictionaries;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "languages")
    public Set<Users> getUserses() {
        return this.userses;
    }

    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }

}
