package md.factorydream.entites;
// Generated Apr 13, 2016 10:19:57 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notes generated by hbm2java
 */
@Entity
@Table(name = "notes", schema = "public"
)
public class Notes implements java.io.Serializable {

    private long id;
    private StatusCod statusCod;
    private Users users;
    private String note;
    private Date lastUpdateDate;
    private Set<GroupNotes> groupNoteses = new HashSet<GroupNotes>(0);

    public Notes() {
    }

    public Notes(long id, Users users, String note) {
        this.id = id;
        this.users = users;
        this.note = note;
    }

    public Notes(long id, StatusCod statusCod, Users users, String note, Date lastUpdateDate, Set<GroupNotes> groupNoteses) {
        this.id = id;
        this.statusCod = statusCod;
        this.users = users;
        this.note = note;
        this.lastUpdateDate = lastUpdateDate;
        this.groupNoteses = groupNoteses;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_status_code")
    public StatusCod getStatusCod() {
        return this.statusCod;
    }

    public void setStatusCod(StatusCod statusCod) {
        this.statusCod = statusCod;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user_last_update", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "note", nullable = false)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update_date", length = 29)
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "notes")
    public Set<GroupNotes> getGroupNoteses() {
        return this.groupNoteses;
    }

    public void setGroupNoteses(Set<GroupNotes> groupNoteses) {
        this.groupNoteses = groupNoteses;
    }

}
