package md.factorydream.entites;
// Generated Apr 13, 2016 10:19:57 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * OrderParameters generated by hbm2java
 */
@Entity
@Table(name = "order_parameters", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {"id_param_name", "id_order"})
)

public class OrderParameters implements java.io.Serializable {

    private long id;
    private Orders orders;
    private ParamNames paramNames;
    private StatusCod statusCod;
    private Users users;
    private String value;
    private String note;
    private Date lastUpdateDate;

    public OrderParameters() {
    }

    public OrderParameters(long id, Orders orders, ParamNames paramNames, Users users, String value) {
        this.id = id;
        this.orders = orders;
        this.paramNames = paramNames;
        this.users = users;
        this.value = value;
    }

    public OrderParameters(long id, Orders orders, ParamNames paramNames, StatusCod statusCod, Users users, String value, String note, Date lastUpdateDate) {
        this.id = id;
        this.orders = orders;
        this.paramNames = paramNames;
        this.statusCod = statusCod;
        this.users = users;
        this.value = value;
        this.note = note;
        this.lastUpdateDate = lastUpdateDate;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_order", nullable = false)
    public Orders getOrders() {
        return this.orders;
    }

    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_param_name", nullable = false)
    public ParamNames getParamNames() {
        return this.paramNames;
    }

    public void setParamNames(ParamNames paramNames) {
        this.paramNames = paramNames;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_status_code")
    public StatusCod getStatusCod() {
        return this.statusCod;
    }

    public void setStatusCod(StatusCod statusCod) {
        this.statusCod = statusCod;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user_last_update", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "value", nullable = false, length = 250)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Column(name = "note", length = 250)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update_date", length = 29)
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

}
