package md.factorydream.entites;
// Generated Apr 13, 2016 10:19:57 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParamNames generated by hbm2java
 */
@Entity
@Table(name = "param_names", schema = "public"
)

public class ParamNames implements java.io.Serializable {

    private long id;
    private Users users;
    private String name;
    private String paramNameDescription;
    private Date lastUpdateDate;
    private Set<TemplateParameters> templateParameterses = new HashSet<TemplateParameters>(0);
    private Set<EventParameters> eventParameterses = new HashSet<EventParameters>(0);
    private Set<OrderParameters> orderParameterses = new HashSet<OrderParameters>(0);

    public ParamNames() {
    }

    public ParamNames(long id, Users users, String name) {
        this.id = id;
        this.users = users;
        this.name = name;
    }

    public ParamNames(long id, Users users, String name, String paramNameDescription, Date lastUpdateDate, Set<TemplateParameters> templateParameterses, Set<EventParameters> eventParameterses, Set<OrderParameters> orderParameterses) {
        this.id = id;
        this.users = users;
        this.name = name;
        this.paramNameDescription = paramNameDescription;
        this.lastUpdateDate = lastUpdateDate;
        this.templateParameterses = templateParameterses;
        this.eventParameterses = eventParameterses;
        this.orderParameterses = orderParameterses;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user_last_update", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "name", nullable = false, length = 250)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "param_name_description", length = 250)
    public String getParamNameDescription() {
        return this.paramNameDescription;
    }

    public void setParamNameDescription(String paramNameDescription) {
        this.paramNameDescription = paramNameDescription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update_date", length = 29)
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "paramNames")
    public Set<TemplateParameters> getTemplateParameterses() {
        return this.templateParameterses;
    }

    public void setTemplateParameterses(Set<TemplateParameters> templateParameterses) {
        this.templateParameterses = templateParameterses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "paramNames")
    public Set<EventParameters> getEventParameterses() {
        return this.eventParameterses;
    }

    public void setEventParameterses(Set<EventParameters> eventParameterses) {
        this.eventParameterses = eventParameterses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "paramNames")
    public Set<OrderParameters> getOrderParameterses() {
        return this.orderParameterses;
    }

    public void setOrderParameterses(Set<OrderParameters> orderParameterses) {
        this.orderParameterses = orderParameterses;
    }

}
