package md.factorydream.entites;
// Generated Apr 13, 2016 10:19:57 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PlanningAppointment generated by hbm2java
 */
@Entity
@Table(name = "planning_appointment", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {"id_appointment", "id_events"})
)
public class PlanningAppointment implements java.io.Serializable {

    private long id;
    private Appointment appointment;
    private Events events;

    public PlanningAppointment() {
    }

    public PlanningAppointment(long id, Appointment appointment, Events events) {
        this.id = id;
        this.appointment = appointment;
        this.events = events;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_appointment", nullable = false)
    public Appointment getAppointment() {
        return this.appointment;
    }

    public void setAppointment(Appointment appointment) {
        this.appointment = appointment;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_events", nullable = false)
    public Events getEvents() {
        return this.events;
    }

    public void setEvents(Events events) {
        this.events = events;
    }

}
