package md.factorydream.entites;
// Generated Apr 13, 2016 10:19:57 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ReportTemplate generated by hbm2java
 */
@Entity
@Table(name = "report_template", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {"name", "id_department"})
)

public class ReportTemplate implements java.io.Serializable {

    private int id;
    private Departments departments;
    private StatusCod statusCod;
    private Users users;
    private String name;
    private String reportTemplateDescription;
    private Date lastUpdateDate;
    private Set<Reports> reportses = new HashSet<Reports>(0);
    private Set<ReportParams> reportParamses = new HashSet<ReportParams>(0);

    public ReportTemplate() {
    }

    public ReportTemplate(int id, Departments departments, Users users, String name) {
        this.id = id;
        this.departments = departments;
        this.users = users;
        this.name = name;
    }

    public ReportTemplate(int id, Departments departments, StatusCod statusCod, Users users, String name, String reportTemplateDescription, Date lastUpdateDate, Set<Reports> reportses, Set<ReportParams> reportParamses) {
        this.id = id;
        this.departments = departments;
        this.statusCod = statusCod;
        this.users = users;
        this.name = name;
        this.reportTemplateDescription = reportTemplateDescription;
        this.lastUpdateDate = lastUpdateDate;
        this.reportses = reportses;
        this.reportParamses = reportParamses;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_department", nullable = false)
    public Departments getDepartments() {
        return this.departments;
    }

    public void setDepartments(Departments departments) {
        this.departments = departments;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_status_code")
    public StatusCod getStatusCod() {
        return this.statusCod;
    }

    public void setStatusCod(StatusCod statusCod) {
        this.statusCod = statusCod;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user_last_update", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "report_template_description", length = 250)
    public String getReportTemplateDescription() {
        return this.reportTemplateDescription;
    }

    public void setReportTemplateDescription(String reportTemplateDescription) {
        this.reportTemplateDescription = reportTemplateDescription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update_date", length = 29)
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "reportTemplate")
    public Set<Reports> getReportses() {
        return this.reportses;
    }

    public void setReportses(Set<Reports> reportses) {
        this.reportses = reportses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "reportTemplate")
    public Set<ReportParams> getReportParamses() {
        return this.reportParamses;
    }

    public void setReportParamses(Set<ReportParams> reportParamses) {
        this.reportParamses = reportParamses;
    }

}
