package md.factorydream.entites;
// Generated Apr 13, 2016 10:19:57 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ReportParams generated by hbm2java
 */
@Entity
@Table(name = "report_params", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {"id_report_template", "id_template_parameter"})
)

public class ReportParams implements java.io.Serializable {

    private long id;
    private ReportTemplate reportTemplate;
    private TemplateParameters templateParameters;
    private String note;

    public ReportParams() {
    }

    public ReportParams(long id, ReportTemplate reportTemplate, TemplateParameters templateParameters) {
        this.id = id;
        this.reportTemplate = reportTemplate;
        this.templateParameters = templateParameters;
    }

    public ReportParams(long id, ReportTemplate reportTemplate, TemplateParameters templateParameters, String note) {
        this.id = id;
        this.reportTemplate = reportTemplate;
        this.templateParameters = templateParameters;
        this.note = note;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_report_template", nullable = false)
    public ReportTemplate getReportTemplate() {
        return this.reportTemplate;
    }

    public void setReportTemplate(ReportTemplate reportTemplate) {
        this.reportTemplate = reportTemplate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_template_parameter", nullable = false)
    public TemplateParameters getTemplateParameters() {
        return this.templateParameters;
    }

    public void setTemplateParameters(TemplateParameters templateParameters) {
        this.templateParameters = templateParameters;
    }

    @Column(name = "note", length = 250)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

}
