package md.factorydream.entites;
// Generated Apr 13, 2016 10:19:57 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ReportOrderParams generated by hbm2java
 */
@Entity
@Table(name = "report_order_params", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "id_report")
)

public class ReportOrderParams implements java.io.Serializable {

    private long id;
    private Colors colors;
    private Customers customers;
    private Diameters diameters;
    private Models models;
    private Reports reports;
    private Threads threads;
    private Types types;
    private String note;

    public ReportOrderParams() {
    }

    public ReportOrderParams(long id, Reports reports) {
        this.id = id;
        this.reports = reports;
    }

    public ReportOrderParams(long id, Colors colors, Customers customers, Diameters diameters, Models models, Reports reports, Threads threads, Types types, String note) {
        this.id = id;
        this.colors = colors;
        this.customers = customers;
        this.diameters = diameters;
        this.models = models;
        this.reports = reports;
        this.threads = threads;
        this.types = types;
        this.note = note;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_color")
    public Colors getColors() {
        return this.colors;
    }

    public void setColors(Colors colors) {
        this.colors = colors;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_customer")
    public Customers getCustomers() {
        return this.customers;
    }

    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_diameter")
    public Diameters getDiameters() {
        return this.diameters;
    }

    public void setDiameters(Diameters diameters) {
        this.diameters = diameters;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_model")
    public Models getModels() {
        return this.models;
    }

    public void setModels(Models models) {
        this.models = models;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_report", unique = true, nullable = false)
    public Reports getReports() {
        return this.reports;
    }

    public void setReports(Reports reports) {
        this.reports = reports;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_thread")
    public Threads getThreads() {
        return this.threads;
    }

    public void setThreads(Threads threads) {
        this.threads = threads;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_type")
    public Types getTypes() {
        return this.types;
    }

    public void setTypes(Types types) {
        this.types = types;
    }

    @Column(name = "note", length = 250)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

}
