package md.factorydream.entites;
// Generated Apr 13, 2016 10:19:57 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", schema = "public"
)

public class Roles implements java.io.Serializable {

    private int id;
    private StatusCod statusCod;
    private Users users;
    private String name;
    private String roleDescription;
    private Date lastUpdateDate;
    private Set<Reports> reportses = new HashSet<Reports>(0);
    private Set<RoleAccess> roleAccesses = new HashSet<RoleAccess>(0);

    public Roles() {
    }

    public Roles(int id, Users users, String name) {
        this.id = id;
        this.users = users;
        this.name = name;
    }

    public Roles(int id, StatusCod statusCod, Users users, String name, String roleDescription, Date lastUpdateDate, Set<Reports> reportses, Set<RoleAccess> roleAccesses) {
        this.id = id;
        this.statusCod = statusCod;
        this.users = users;
        this.name = name;
        this.roleDescription = roleDescription;
        this.lastUpdateDate = lastUpdateDate;
        this.reportses = reportses;
        this.roleAccesses = roleAccesses;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_status_code")
    public StatusCod getStatusCod() {
        return this.statusCod;
    }

    public void setStatusCod(StatusCod statusCod) {
        this.statusCod = statusCod;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user_last_update", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "role_description")
    public String getRoleDescription() {
        return this.roleDescription;
    }

    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update_date", length = 29)
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
    public Set<Reports> getReportses() {
        return this.reportses;
    }

    public void setReportses(Set<Reports> reportses) {
        this.reportses = reportses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
    public Set<RoleAccess> getRoleAccesses() {
        return this.roleAccesses;
    }

    public void setRoleAccesses(Set<RoleAccess> roleAccesses) {
        this.roleAccesses = roleAccesses;
    }

}
