package md.factorydream.entites;
// Generated Apr 13, 2016 10:19:57 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * StatusGroup generated by hbm2java
 */
@Entity
@Table(name = "status_group", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "name")
)

public class StatusGroup implements java.io.Serializable {

    private short id;
    private Users users;
    private String name;
    private String statusGroupDescription;
    private Date lastUpdateDate;
    private Set<StatusCod> statusCods = new HashSet<StatusCod>(0);

    public StatusGroup() {
    }

    public StatusGroup(short id, Users users, String name, String statusGroupDescription) {
        this.id = id;
        this.users = users;
        this.name = name;
        this.statusGroupDescription = statusGroupDescription;
    }

    public StatusGroup(short id, Users users, String name, String statusGroupDescription, Date lastUpdateDate, Set<StatusCod> statusCods) {
        this.id = id;
        this.users = users;
        this.name = name;
        this.statusGroupDescription = statusGroupDescription;
        this.lastUpdateDate = lastUpdateDate;
        this.statusCods = statusCods;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public short getId() {
        return this.id;
    }

    public void setId(short id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user_last_update", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "name", unique = true, nullable = false, length = 60)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "status_group_description", nullable = false)
    public String getStatusGroupDescription() {
        return this.statusGroupDescription;
    }

    public void setStatusGroupDescription(String statusGroupDescription) {
        this.statusGroupDescription = statusGroupDescription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update_date", length = 29)
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "statusGroup")
    public Set<StatusCod> getStatusCods() {
        return this.statusCods;
    }

    public void setStatusCods(Set<StatusCod> statusCods) {
        this.statusCods = statusCods;
    }

}
