package md.factorydream.entites;
// Generated Apr 13, 2016 10:19:57 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Statuses generated by hbm2java
 */
@Entity
@Table(name = "statuses", schema = "public"
)

public class Statuses implements java.io.Serializable {

    private short id;
    private Users users;
    private String name;
    private String statusDescription;
    private Date lastUpdateDate;
    private Set<StatusCod> statusCods = new HashSet<StatusCod>(0);

    public Statuses() {
    }

    public Statuses(short id, Users users, String name) {
        this.id = id;
        this.users = users;
        this.name = name;
    }

    public Statuses(short id, Users users, String name, String statusDescription, Date lastUpdateDate, Set<StatusCod> statusCods) {
        this.id = id;
        this.users = users;
        this.name = name;
        this.statusDescription = statusDescription;
        this.lastUpdateDate = lastUpdateDate;
        this.statusCods = statusCods;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public short getId() {
        return this.id;
    }

    public void setId(short id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user_last_update", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "name", nullable = false, length = 60)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "status_description")
    public String getStatusDescription() {
        return this.statusDescription;
    }

    public void setStatusDescription(String statusDescription) {
        this.statusDescription = statusDescription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update_date", length = 29)
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "statuses")
    public Set<StatusCod> getStatusCods() {
        return this.statusCods;
    }

    public void setStatusCods(Set<StatusCod> statusCods) {
        this.statusCods = statusCods;
    }

}
