package md.factorydream.entites;
// Generated Apr 13, 2016 10:19:57 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TemplateParameters generated by hbm2java
 */
@Entity
@Table(name = "template_parameters", schema = "public"
)

public class TemplateParameters implements java.io.Serializable {

    private long id;
    private ParamNames paramNames;
    private StatusCod statusCod;
    private Users users;
    private String value;
    private String note;
    private Date lastUpdateDate;
    private Set<ReportParams> reportParamses = new HashSet<ReportParams>(0);

    public TemplateParameters() {
    }

    public TemplateParameters(long id, ParamNames paramNames, Users users, String value) {
        this.id = id;
        this.paramNames = paramNames;
        this.users = users;
        this.value = value;
    }

    public TemplateParameters(long id, ParamNames paramNames, StatusCod statusCod, Users users, String value, String note, Date lastUpdateDate, Set<ReportParams> reportParamses) {
        this.id = id;
        this.paramNames = paramNames;
        this.statusCod = statusCod;
        this.users = users;
        this.value = value;
        this.note = note;
        this.lastUpdateDate = lastUpdateDate;
        this.reportParamses = reportParamses;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_param_name", nullable = false)
    public ParamNames getParamNames() {
        return this.paramNames;
    }

    public void setParamNames(ParamNames paramNames) {
        this.paramNames = paramNames;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_status_code")
    public StatusCod getStatusCod() {
        return this.statusCod;
    }

    public void setStatusCod(StatusCod statusCod) {
        this.statusCod = statusCod;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user_last_update", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "value", nullable = false, length = 250)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Column(name = "note", length = 250)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update_date", length = 29)
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "templateParameters")
    public Set<ReportParams> getReportParamses() {
        return this.reportParamses;
    }

    public void setReportParamses(Set<ReportParams> reportParamses) {
        this.reportParamses = reportParamses;
    }

}
