package md.factorydream.entites;
// Generated Apr 27, 2016 2:37:35 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TranslateDictionary generated by hbm2java
 */
@Entity
@Table(name = "translate_dictionary", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {"id_lang", "translate_code"})
)
public class TranslateDictionary implements java.io.Serializable {

    private long id;
    private Languages languages;
    private String translateCode;
    private String translateValue;

    public TranslateDictionary() {
    }

    public TranslateDictionary(long id, String translateCode, String translateValue) {
        this.id = id;
        this.translateCode = translateCode;
        this.translateValue = translateValue;
    }

    public TranslateDictionary(long id, Languages languages, String translateCode, String translateValue) {
        this.id = id;
        this.languages = languages;
        this.translateCode = translateCode;
        this.translateValue = translateValue;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_lang")
    public Languages getLanguages() {
        return this.languages;
    }

    public void setLanguages(Languages languages) {
        this.languages = languages;
    }

    @Column(name = "translate_code", nullable = false, length = 100)
    public String getTranslateCode() {
        return this.translateCode;
    }

    public void setTranslateCode(String translateCode) {
        this.translateCode = translateCode;
    }

    @Column(name = "translate_value", nullable = false)
    public String getTranslateValue() {
        return this.translateValue;
    }

    public void setTranslateValue(String translateValue) {
        this.translateValue = translateValue;
    }

}
